CREATE TABLE USERS (
	USER_ID integer PRIMARY KEY AUTOINCREMENT,
	USERNAME varchar UNIQUE,
	PASSWORD varchar,
	ROLE_ID integer,
	EMAIL varchar,
	AVATAR blob
);

CREATE TABLE TAGS (
	TAG_ID integer PRIMARY KEY AUTOINCREMENT,
	TAG_NAME varchar
);

CREATE TABLE USERS_SOURCES (
	USER_SOURCE_ID integer PRIMARY KEY AUTOINCREMENT,
	SOURCE_ID integer,
	USER_ID integer,
	NAME varchar,
	DESCRIPTION text
);

CREATE TABLE ROLES (
	ROLE_ID integer PRIMARY KEY AUTOINCREMENT,
	ROLE_NAME varchar
);

CREATE TABLE NEWS (
	NEWS_ID integer PRIMARY KEY AUTOINCREMENT,
	SOURCE_ID integer,
	TITLE text,
	DESCRIPTION blob,
	LINK varchar,
	RSS_DATA blob
);

CREATE TABLE AUTH (
	AUTH_ID integer,
	USER_ID integer,
	TOKEN varchar,
	CREATION_TIME datetime
);

CREATE TABLE USERS_NEWS (
	USER_NEWS_ID integer PRIMARY KEY AUTOINCREMENT,
	USER_ID integer,
	NEWS_ID integer,
	FAVOURITE integer
);

CREATE TABLE NEWS_TAGS (
	NEWS_TAG_ID integer PRIMARY KEY AUTOINCREMENT,
	USER_ID blob,
	NEWS_ID integer,
	TAG_ID integer
);

CREATE TABLE SOURSES_TAGS (
	SOURSE_TAG_ID integer,
	USER_ID integer,
	SOURCE_ID integer,
	TAG_ID integer
);

CREATE TABLE SOURCES (
	SOURCE_ID integer PRIMARY KEY AUTOINCREMENT,
	RSS_URL varchar
);
