CREATE TABLE USERS (
	USER_ID integer PRIMARY KEY AUTOINCREMENT,
	USERNAME varchar,
	PASSWORD varchar,
	ROLE_ID integer,
	EMAIL varchar,
	AVATAR_REF varchar
);

CREATE TABLE SUBSCRIPTIONS (
	SUBSCRIPTION_ID integer PRIMARY KEY AUTOINCREMENT,
	USER_ID integer,
	TAG_ID integer
);

CREATE TABLE TAGS (
	TAG_ID blob PRIMARY KEY AUTOINCREMENT,
	TAG_NAME varchar
);

CREATE TABLE SUBSCRIPTION_TAG_MAP (
	MAPPING_ID integer,
	SUBSCRIPTION_ID integer,
	TAG_ID integer
);

CREATE TABLE ROLES (
	ROLE_ID integer PRIMARY KEY AUTOINCREMENT,
	ROLE_NAME varchar
);

CREATE TABLE NEWS (
	NEWS_ID integer PRIMARY KEY AUTOINCREMENT,
	TAG_ID integer,
	LINK varchar,
	CREATION_TIME datetime
);

CREATE TABLE NEWS_SITES (
	SITE_ID integer PRIMARY KEY AUTOINCREMENT,
	RSS_LINK varchar
);

CREATE TABLE AUTH (
	AUTH_ID integer,
	USER_ID integer,
	TOKEN varchar,
	CREATION_TIME datetime
);

CREATE TABLE FAVORITES (
	FAVORITE_ID integer PRIMARY KEY AUTOINCREMENT,
	NEWS_ID integer,
	USER_ID integer
);


