DROP TABLE IF EXISTS USERS;

DROP TABLE IF EXISTS TAGS;

DROP TABLE IF EXISTS USERS_SOURCES;

DROP TABLE IF EXISTS ROLES;

DROP TABLE IF EXISTS NEWS;

DROP TABLE IF EXISTS AUTH;

DROP TABLE IF EXISTS USERS_NEWS;

DROP TABLE IF EXISTS NEWS_TAGS;

DROP TABLE IF EXISTS SOURSES_TAGS;

DROP TABLE IF EXISTS SOURCES;
