#+TITLE: Техническое задание

#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage{polyglossia}
#+LATEX_HEADER: \setmainlanguage{russian}
#+LATEX_HEADER: \setotherlanguage{english}
#+LATEX_HEADER: \setkeys{russian}{babelshorthands=true}
#+LATEX_HEADER: \PolyglossiaSetup{russian}{indentfirst=true}
#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \setmainfont{Liberation Serif}
#+LATEX_HEADER: \usepackage{minted}


* Введение

Web приложение предназначенное для чтения новостей из различных источников при
помощи технологии RSS.

* Общее описание

Для взаимодействия пользователя с приложением используется Web-интерфейс.
Так же для программного взаимодействия присутствует REST-API сервера.
Web-интерфейс использует REST-API для получения и изменения данных.

Приложение имеет следующие функциональные возможности:
- регистрация и авторизация пользователя
- возможность добавления источников новостей
- загрузка новостей из источников
- возможность тегирования новостей и источников
- просмотр и фильтрация новостей

** Данные

* Api интерфейсы
Api имеет архитектуру REST-API.
Необходимы присутствовать следующие ресурсы:
- sources
- news
- login
- user

** sources

В данном ресурсе предоставляются источники которые использует пользователь.
Иммет следующие интерфейсы:
- ~GET /sources~

  - Описание:

    Получение списка ресурсов пользователя.

  - Входные параметры:

    Параметры авторизации

  - Выходные параметры:

    Список обектов с информацией о ресурсах

- ~POST /sources~

  - Описание:

    Добавить ресурс

  - Входные параметры:
     
    Параметры авторизации

  - Выходные параметры:

    Информация о добавленом ресурсе.

- ~GET /sources/:idSource~

  - Описание:

    Получить информацию о ресурсе с id

  - Входные параметры:

    idSource - id ресурса

    Параметры авторизации

  - Выходные параметры:

    Информация о ресурсе с id = idSource

- ~DELETE /sources/:idSource~

  - Описание:

    Удалить ресурс с id = idSource из ресурсов пользователя.
   
  - Входные параметры:

    idSource - id ресурса
    
    Параметры авторизации

  - Выходные параметры:

    None

- ~PATCH /sources/:idSource~

  - Описание:

    Обновить информацию о ресурсе.

    Примечание: после обновления адреса ресурса может изменится

  - Входные параметры:

    idSource - id ресурса

    Параметры авторизации

  - Выходные параметры:
    
    Информация о изменённом ресурсе с id = idSource

Описание моделей:
# TODO
** news

В данном ресурсе предоставляются новости пользователя.
Иммет следующие интерфейсы:
- ~GET /news~

  - Описание:

    Получение списка новостей пользователя.

  - Входные параметры:

    Параметры авторизации

    Необязательные параметры:
    - id ресурса
    - теги
    - избранное
    - прочитано или нет
    - ...

  - Выходные параметры:

    Список обектов с информацией о новостях

- ~GET /news/:idNews~

  - Описание:

    Получить информацию о новости c id = idNews

  - Входные параметры:

    Параметры авторизации

  - Выходные параметры:

    Информация о новости с id = idSource

- ~PATCH /news/:idNews~

  - Описание:

    Изменение информации о новости:
    - теги
    - избранное
    - прочитано или нет
    - ...

  - Входные параметры:

    Параметры авторизации

    Обновлённые параметры

  - Выходные параметры:

    Изменённая информация о новости с id = idSource
    
- ~DELETE /news/:idNews~

  - Описание:

    Удаляет новость у пользователя

  - Входные параметры:

    Параметры авторизации

  - Выходные параметры:

    None

Описание моделей:
# TODO
** login

Ресурс для авторизации пользователя
Иммет следующие интерфейсы:
- ~POST /login~

  - Описание:
  # TODO

  - Входные параметры:
  # TODO

  - Выходные параметры:
  # TODO

Описание моделей:
# TODO
** user

Ресурс для получения информации о пользователях.
Для обычных пользователей доступна информация только о самих себе.
Иммет следующие интерфейсы:
- ~GET /users~

  - Описание:
  # TODO

  - Входные параметры:
  # TODO

  - Выходные параметры:
  # TODO
- ~POST /users~

  - Описание:
  # TODO

  - Входные параметры:
  # TODO

  - Выходные параметры:
  # TODO
- ~GET /users/:idUser~

  - Описание:
  # TODO

  - Входные параметры:
  # TODO

  - Выходные параметры:
  # TODO
- ~PUT /users/:idUser~

  - Описание:
  # TODO

  - Входные параметры:
  # TODO

  - Выходные параметры:
  # TODO
- ~DELETE /users/:idUser~

  - Описание:
  # TODO

  - Входные параметры:
  # TODO

  - Выходные параметры:
  # TODO

Описание моделей:
# TODO
